/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p_p_3;

import java.util.concurrent.*;

import static java.util.concurrent.TimeUnit.SECONDS;
/**
 *
 * @author Epps
 */
public class loading_screen extends javax.swing.JFrame {

    /**
     * Creates new form loading_screen
     */
    public loading_screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loading_bar = new javax.swing.JProgressBar();
        loading_Label = new javax.swing.JLabel();
        component_checking_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loading_bar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                loading_barPropertyChange(evt);
            }
        });

        loading_Label.setText("Loading...");

        component_checking_label.setText("Checking components");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loading_bar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(loading_Label)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(component_checking_label)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(loading_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(component_checking_label)
                .addGap(14, 14, 14)
                .addComponent(loading_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loading_barPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_loading_barPropertyChange
        // TODO add your handling code here:
        TimeUnit timer = TimeUnit.SECONDS;
        //timer.SECONDS
        boolean firstcheck = Search.DatabaseCheck();
        boolean secondcheck = Log.DatabaseCheck();
        
        if(firstcheck = true){
            //timer. schedule(new DisplayCountdown(), 0, 1000);
            component_checking_label.setText("Database found!");
        }
        else{
            component_checking_label.setText("Database not found... Exiting");
        }
        
        if(secondcheck==true){
            component_checking_label.setText("Log created");
        }
        Log.createFile();
        
    }//GEN-LAST:event_loading_barPropertyChange

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel component_checking_label;
    private javax.swing.JLabel loading_Label;
    private javax.swing.JProgressBar loading_bar;
    // End of variables declaration//GEN-END:variables
}
